# docker-compose.yml
version: '3.8'

services:
  # Python/Flaskアプリケーションのサービス
  backend:
    build: ./backend  # ./backend/Dockerfile を使ってビルド
    ports:
      - "5000:5000"  # PCの5000番ポートとコンテナの5000番ポートを繋ぐ
    volumes:
      - ./backend/src:/app  # PCのソースコードの変更をコンテナに即時反映させる

